version: "3"
services:
  configserver:
    container_name: cd-config-server
    ports:
      - "${HTTPPORT}:3000"
    environment:
      - USERAGENT=${USERAGENT}
      - GITHUBUSERNAME=${GITHUBUSERNAME}
      - CACHE_TTL=${CACHE_TTL}
      - RATE_LIMIT_MS=${RATE_LIMIT_MS}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX}
    image: markusfalk/cd-config-server:latest
