version: '3'
services:
  configserver:
    container_name: cd-config-server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '${HTTPPORT}:3000'
    environment:
      - SOURCE=${SOURCE}
    volumes:
      - ${VOLUME}:/app/dist/configfiles
