name: Release

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.4
        with:
          node-version: ^14

      - name: install
        run: npm ci

      - name: lint
        run: npm run lint

      - name: test
        run: |
          npm run test
          npm run test:e2e

      - name: tag release
        run: npm run release -- --dry-run

      - name: package-version
        uses: nyaa8/package-version@v1.0.3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESSTOKEN }}

      - name: docker build
        uses: docker/build-push-action@v2.2.1
        with:
          push: true
          tags: |
            markusfalk/cd-config-server:latest
            markusfalk/cd-config-server:${{ env.PACKAGE_VERSION }}
            
      - name: update Readme on dockerhub
        uses: peter-evans/dockerhub-description@v2.4.1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESSTOKEN }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

